version: '3'

services:
  redis:
    # https://hub.docker.com/_/redis
    image: redis:7.4.0
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf